version: "3.10"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.31
    container_name: flask-backend-db
    environment:
      MYSQL_ROOT_PASSWORD: Namrata.31
      MYSQL_DATABASE: emp
    ports:
      - "3307:3306"
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flask-backend
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db




  






